# Generated by Django 2.0.7 on 2019-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('jogador', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=3)),
                ('tamanho', models.CharField(max_length=1)),
            ],
        ),
    ]
