# Generated by Django 2.1.2 on 2019-01-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='camisa',
            name='jogador',
            field=models.CharField(max_length=30),
        ),
    ]
