# Generated by Django 2.1.2 on 2019-01-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20190124_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casual',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
